### PR TITLE
Fix/aux request cache

### LINKED ISSUE #180: Caching of auxiliary requests
https://git.sinergise.com/team-6/eobrowser3/-/merge_requests/598#note_216491

When creating a layer, the layer usually doesn't have mosaickingOrder, upsampling and downsampling set. We do `updateLayerFromServiceIfNeeded`, but it doesn't set either. The `/layers` and getCapabilities responses are saved in the memory. 

However, when we make a getMap request, the method _again_ calls `/layers`. Because of this line: https://github.com/sentinel-hub/sentinelhub-js/blob/9cd7853478f79cf444786d6f2fcf5c5f525d380d/src/layer/AbstractSentinelHubV3Layer.ts#L197

However, because we use storage cache for `getMap`, it reads the `/layers` response from *storage*. However, the one saved there is from when we initially loaded the instance, without the new layer.

---------

I think the latest assumption is that we should only cache `getCapabilties/layer` to memory, but as you found out `fetchLayerParamsFromSHServiceV3` is cached to `cacheApi` because of the `reqConfig` passed from `getMap`, so I think we should just hardcode caching to memory for `fetchLayerParamsFromSHServiceV3`, this should be ok as it is a protected method.

The following changes should work.

```
 protected async fetchLayerParamsFromSHServiceV3(reqConfig: RequestConfiguration): Promise<any> {
...
    const requestConfig: AxiosRequestConfig = {
      responseType: 'json',
      headers: headers,
      ...getAxiosReqParams(reqConfig, { ...CACHE_CONFIG_30MIN, targets: [CacheTarget.MEMORY] }),
    };<
```

```
export const getAxiosReqParams = (
  reqConfig: RequestConfiguration,
  defaultCache: CacheConfig,
): AxiosRequestConfig => {
...

  if (reqConfigWithDefault.cache && reqConfigWithDefault.cache.expiresIn) {
    axiosReqConfig.cache.expiresIn = reqConfigWithDefault.cache.expiresIn;
  }
  if (reqConfigWithDefault.cache && reqConfigWithDefault.cache.targets) {
    axiosReqConfig.cache.targets = reqConfigWithDefault.cache.targets;
  }
```

------

Is there really a point in passing the `getMap`s `reqConfig` to `fetchLayerParamsFromSHServiceV3` at all, though? If we are deciding to cache by default for the user, we could literally just have it hardcoded to use memory regardless.

### PR DESCRIPTION
**Pull request by guss84**
resolve #180 

- Introduces `CACHE_CONFIG_30MIN_MEMORY`
- Removes cache config received from `getMap` in `fetchLayerParamsFromSHServiceV3` and assign  `CACHE_CONFIG_30MIN_MEMORY` to the cache property of `reqConfig`

### CODE REVIEW

File: src/layer/AbstractSentinelHubV3Layer.ts [hunk 1]
```diff
@@ -110,10 +109,17 @@ export class AbstractSentinelHubV3Layer extends AbstractLayer {
     const headers = {
       Authorization: `Bearer ${authToken}`,
     };
+
+    // reqConfig might include the cache config from getMap, which could cache instances/${this.instanceId}/layers
+    // we do not want this as layer updates will not invalidate this cache, so we rathger cache to memory
+    const reqConfigWithMemoryCache = {
+      ...reqConfig,
+      cache: CACHE_CONFIG_30MIN_MEMORY,
```
Comment (dgostencnik) [inline src/layer/AbstractSentinelHubV3Layer.ts:117]: What if caching is disabled in `reqConfig` by setting `expiresIn` to 0 ? This will now override that setting and cache it in memory for 30mins. Not sure if this is expected behaviour.

**Review by dgostencnik — COMMENTED** [review]
It would probably make sense to write tests for this, but it might be quite a challenging task. I'm not sure if we can tell easily from where the cache is being served.

File: src/layer/AbstractSentinelHubV3Layer.ts (hunk 1 above)
Comment (guss84) [reply src/layer/AbstractSentinelHubV3Layer.ts:117]: Good point, and I am not sure what the best approach here would be. The information needed from `fetchLayerParamsFromSHServiceV3` is stored in the layer's instance, so `fetchLayerParamsFromSHServiceV3` could only called if a new instance is created.

Do you think removing cache here is a viable option, or should we only override cache if cache was set in `reqConfig` unless it is `expiresIn: 0`?

Comment (dgostencnik) [reply src/layer/AbstractSentinelHubV3Layer.ts:117]: Yes, I think if cache is disabled for request, I wouldn't override it in `fetchLayerParamsFromSHServiceV3`.

**Comment by guss84** [comment]
> It would probably make sense to write tests for this, but it might be quite a challenging task. I'm not sure if we can tell easily from where the cache is being served.

I have added 2 test cases, one for checking if it is cached to memory by default and the other to test that caching is disabled.

File: src/layer/AbstractSentinelHubV3Layer.ts (hunk 1 above)
Comment (guss84) [reply src/layer/AbstractSentinelHubV3Layer.ts]: Made the changes so that `fetchLayerParamsFromSHServiceV3` will not be cached if caching is disabled by setting `expiresIn: 0`

File: src/layer/__tests__/cache.ts [hunk 2]
```diff
@@ -496,3 +497,56 @@ describe('Unit test for cacheStillValid', () => {
...
+describe('Unit test for aux request caching', () => {
+  beforeEach(async () => {
+    Object.assign(global, makeServiceWorkerEnv(), fetch); // adds these functions to the global object
+    await invalidateCaches();
+    setAuthToken(undefined);
+  });
+  it('It should be cache aux request to memory by default', async () => {
+    setAuthToken(EXAMPLE_TOKEN);
+    const { layer, mockedResponse, expectedLayerParams } = constructFixtureUpdateLayerFromServiceIfNeeded({});
+    const requestsConfig = {
```
Comment (dgostencnik) [inline src/layer/__tests__/cache.ts:510]: You could expand this test a bit by using  it.each and use different requestsConfigs as an input
listOfRequstConfigs=[
{} , 
null, 
undefined, 
{ retries: 1 },
{
      cache: {
        expiresIn: 60,
      },
   }
... all other combination of expiresIn and target params,
]
  
 it.each([....listOfRequstConfigs])('It should be cache aux request to memory by default', async requestsConfig => {....})

fftr

**Review by dgostencnik — APPROVED** [review]

File: src/layer/__tests__/cache.ts (hunk 2 above)
Comment (guss84) [reply src/layer/__tests__/cache.ts]: I expanded the test as suggested and added other `requestsConfigs`
